let books = [
  {
    url: 'https://anapioficeandfire.com/api/books/1',
    name: 'A Game of Thrones',
    isbn: '978-0553103540',
    authors: ['George R. R. Martin'],
    numberOfPages: 694,
    publisher: 'Bantam Books',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '1996-08-01T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/2',
    name: 'A Clash of Kings',
    isbn: '978-0553108033',
    authors: ['George R. R. Martin'],
    numberOfPages: 768,
    publisher: 'Bantam Books',
    country: 'United States',
    mediaType: 'Hardback',
    released: '1999-02-02T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/3',
    name: 'A Storm of Swords',
    isbn: '978-0553106633',
    authors: ['George R. R. Martin'],
    numberOfPages: 992,
    publisher: 'Bantam Books',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '2000-10-31T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/4',
    name: 'The Hedge Knight',
    isbn: '978-0976401100',
    authors: ['George R. R. Martin'],
    numberOfPages: 164,
    publisher: 'Dabel Brothers Publishing',
    country: 'United States',
    mediaType: 'GraphicNovel',
    released: '2005-03-09T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/5',
    name: 'A Feast for Crows',
    isbn: '978-0553801507',
    authors: ['George R. R. Martin'],
    numberOfPages: 784,
    publisher: 'Bantam Books',
    country: 'United Status',
    mediaType: 'Hardcover',
    released: '2005-11-08T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/6',
    name: 'The Sworn Sword',
    isbn: '978-0785126508',
    authors: ['George R. R. Martin'],
    numberOfPages: 152,
    publisher: 'Marvel',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '2008-06-18T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/7',
    name: 'The Mystery Knight',
    isbn: '978-0765360267',
    authors: ['George R. R. Martin'],
    numberOfPages: 416,
    publisher: 'Tor Fantasy',
    country: 'United States',
    mediaType: 'Paperback',
    released: '2011-03-29T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/8',
    name: 'A Dance with Dragons',
    isbn: '978-0553801477',
    authors: ['George R. R. Martin'],
    numberOfPages: 1040,
    publisher: 'Bantam Books',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '2011-07-12T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/9',
    name: 'The Princess and the Queen',
    isbn: '978-0765332066',
    authors: ['George R. R. Martin'],
    numberOfPages: 784,
    publisher: 'Tor Books',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '2013-12-03T00:00:00',
  },
  {
    url: 'https://anapioficeandfire.com/api/books/10',
    name: 'The Rogue Prince',
    isbn: '978-0345537263',
    authors: ['George R. R. Martin'],
    numberOfPages: 832,
    publisher: 'Bantam Books',
    country: 'United States',
    mediaType: 'Hardcover',
    released: '2014-06-17T00:00:00',
  },
];

module.exports = books;
